name: Changelog

on:
    pull_request:
        branches:
            - 'dev'
        types: [ 'closed' ]

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    update_changelog:
        name: Update changelog
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true
        steps:
            -   name: Checkout codebase
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Identify last release cut
                id: last_release
                uses: actions/github-script@v7
                with:
                    script: |
                        // Retrieve all releases
                        // const response = await github.rest.repos.listReleases({
                        //     owner: context.repo.owner,
                        //     repo: context.repo.repo,
                        // });
                        const response = await github.paginate(
                            github.rest.repos.listReleases,
                            {
                                owner: context.repo.owner,
                                repo: context.repo.repo,
                            },
                        );
                        console.log(response);
                        const { data: releases } = response;
                        // Filter releases for those with a version tag where the patch number = 0 (e.g., v1.2.0)
                        const filteredReleases = releases.filter(release => {
                            const match = release.tag_name.match(/^\d+\.\d+\.0$/);
                            return match !== null;
                        });
                
                        // If there's at least one matching release, log them; otherwise fail
                        if (filteredReleases.length !== 0) {
                            core.setOutput("version_tag", filteredReleases[0].tag_name);
                            console.log("version_tag -> " + filteredReleases[0].tag_name);
                        } else {
                            core.setFailed("No releases with patch version 0 found.");
                        }
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: Identify current version tag
                id: current_release
                run: |
                    CURRENT_VERSION_TAG=$(grep '^versionName=' app/gradle.properties | cut -d'=' -f2)
                    echo "version_tag=${CURRENT_VERSION_TAG}" >> $GITHUB_OUTPUT
                    echo "version_tag -> ${CURRENT_VERSION_TAG}"

            -   name: Identify commits
                id: commits
                uses: actions/github-script@v7
                with:
                    script: |
                        const lastVersionTag = process.env.LAST_VERSION_TAG;
                        const currentVersionTag = process.env.CURRENT_VERSION_TAG;
                        
                        console.log(`Last version tag: ${lastVersionTag}`);
                        console.log(`Current version tag: ${currentVersionTag}`);
                        
                        const { data: last_release_commit } = await github.rest.repos.getCommit({
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            ref: `refs/tags/${lastVersionTag}`,
                        })
                        const { data: current_release_commit } = await github.rest.repos.getCommit({
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            ref: `refs/heads/dev`,
                        })
                        console.log(last_release_commit);
                        console.log(current_release_commit);
                env:
                    LAST_VERSION_TAG: ${{ steps.last_release.outputs.version_tag }}
                    CURRENT_VERSION_TAG: ${{ steps.current_release.outputs.version_tag }}
