name: Comment-based Workflow

on:
    issue_comment:
        types: [ created ]

jobs:
    comment-job:
        runs-on: ubuntu-latest

        steps:
            -   name: Set up Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: '18'

            -   name: Get PR details
                id: pr
                env:
                    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    number="${{ github.event.issue.number }}"
                    gh api repos/${{ github.repository }}/pulls/$number >pr.json
                    echo "branch=$(jq -r .head.ref pr.json)"     >>"$GITHUB_OUTPUT"
                    echo "remote=$(jq -r .head.repo.full_name pr.json)" >>"$GITHUB_OUTPUT"
            -   name: Commit and push updated screenshots
                run: |
                    node -e "
                    console.log('---- github');
                    console.log(process.env.GITHUB_EVENT_ISSUE);
                    console.log('---- github.event.issue');
                    console.log(process.env.GITHUB_EVENT_ISSUE);
                    console.log('---- github.event.issue.pull_request');
                    console.log(process.env.GITHUB_EVENT_ISSUE_PULL_REQUEST);
                    "
                    echo ${{ steps.pr.outputs.remote }}
                    echo ${{ steps.pr.outputs.branch }}
                env:
                    GITHUB: ${{ toJson(github) }}
                    GITHUB_EVENT_ISSUE: ${{ toJson(github.event.issue) }}
                    GITHUB_EVENT_ISSUE_PULL_REQUEST: ${{ toJson(github.event.issue.pull_request) }}