name: Comment-based Workflow

on:
    issue_comment:
        types: [ created ]

jobs:
    comment-job:
        runs-on: ubuntu-latest

        steps:
            -   name: Set up Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: '18'

            -   name: Remove triggering comment
                uses: actions/github-script@v6
                with:
                    script: |
                        core.info("context:");
                        core.info(context);
                        await github.rest.issues.deleteComment({
                            owner: context.repo.owner,
                            repo: context.repo.name,
                            comment_id: context.payload.comment.id,
                        })

            -   name: Get branch name
                id: branch
                uses: actions/github-script@v6
                with:
                    script: |
                        const number = context.issue.number;
                        const response = await github.rest.pulls.get({
                            owner: context.repo.owner,
                            repo: context.repo.name,
                            pull_number: number
                        });
                        core.setOutput("ref", response.data.head.ref);

            -   name: Commit and push updated screenshots
                run: |
                    node -e "
                    console.log('---- github');
                    console.log(process.env.GITHUB_EVENT_ISSUE);
                    console.log('---- github.event.issue');
                    console.log(process.env.GITHUB_EVENT_ISSUE);
                    console.log('---- github.event.issue.pull_request');
                    console.log(process.env.GITHUB_EVENT_ISSUE_PULL_REQUEST);
                    "
                    echo ${{ steps.branch.outputs.ref }}
                env:
                    GITHUB: ${{ toJson(github) }}
                    GITHUB_EVENT_ISSUE: ${{ toJson(github.event.issue) }}
                    GITHUB_EVENT_ISSUE_PULL_REQUEST: ${{ toJson(github.event.issue.pull_request) }}