name: On-demand Workflow

on:
    workflow_dispatch:
        inputs:
            gradle_tasks:
                description: 'Array with lists of tasks to run'
                required: false

jobs:
    onDemandRunner:
        name: Run requested gradle tasks
        runs-on: ubuntu-latest
        concurrency:
            group: compilationCheck-${{ github.workflow }}-${{ github.base_ref }}
            cancel-in-progress: true

        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-tags: false
                    lfs: true

            -   name: set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4

            -   name: Build with Gradle
                run: |
                    echo '${{ inputs.gradle_tasks }}' | jq -c '.[]' | while read -r tasks; do
                        exec 3>&1
                        output=$(
                            ./gradlew $(echo $tasks | jq -r '.[]') --scan 2>&1 \
                            | tee >(cat >&3)
                        )
                        exec 3>&-
                        
                        # Initialize variables with empty values
                        echo "failed_task=" >> $GITHUB_OUTPUT
                        echo "report_path=" >> $GITHUB_OUTPUT
                        
                        # Check if there's a failure message before attempting to parse it
                        if echo "$output" | grep -q "Execution failed for task"; then
                            # Extract failed task only if the failure message exists
                            failed_task=$(echo "$output" | grep "Execution failed for task" | sed -E "s/.*task '(.*)'.*/\1/")
                        
                            # Extract report path and strip file:// prefix
                            report_path=$(echo "$output" | grep -o "file:///.*\.html" | tac | head -n 1 | sed 's|file://||' | sed 's|/index.html$||' || echo "")                    
                        
                            # Update outputs only if we found the values
                            if [ ! -z "$failed_task" ]; then
                                echo "failed_task=$failed_task" >> $GITHUB_OUTPUT
                            fi
                            if [ ! -z "$report_path" ]; then
                                echo "report_path=$report_path" >> $GITHUB_OUTPUT
                            fi
                        fi
                    done

