name: Update changelog

on:
    pull_request:
        branches:
            - 'dev'
        types: [ 'closed' ]

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    update_changelog:
        name: Update changelog
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        # Only run if the PR is merged
        if: github.event.pull_request.merged == true

        steps:
            - name: Check out codebase
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Identify current version tag
              id: current_release
              shell: bash
              run: |
                  # Safely extract versionName from gradle.properties
                  CURRENT_VERSION_TAG=$(grep '^versionName=' app/gradle.properties | cut -d'=' -f2)
                  if [ -z "$CURRENT_VERSION_TAG" ]; then
                    echo "Error: Could not find 'versionName' in app/gradle.properties."
                    exit 1
                  fi
                  echo "version_tag=${CURRENT_VERSION_TAG}" >> "$GITHUB_OUTPUT"

            - name: Create release draft with proper changelog
              id: unified
              uses: actions/github-script@v7
              with:
                  script: |
                      const changelog = require('.github/workflows/releaseNotes/releaseNotes.js')
                      await changelog.createRelease({
                        github: github,
                        context: context,
                        tagName: process.env.CURRENT_VERSION_TAG,
                        isDraft: true,
                      });
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CURRENT_VERSION_TAG: ${{ steps.current_release.outputs.version_tag }}
