name: Release Draft

on:
    pull_request:
        branches:
            - 'dev'
            - 'release_*'
        types: [ 'closed' ]

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    release_draft:
        name: Update release draft
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout codebase
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Get version tag
                id: version_tag
                run: |
                    VERSION_LINE=$(grep '^versionName=' app/gradle.properties)
                    CURRENT_VERSION=${VERSION_LINE#versionName=}
                    echo "version_tag=${CURRENT_VERSION}" >> $GITHUB_OUTPUT

            -   uses: release-drafter/release-drafter@v6
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    config-name: workflows/releaseDrafter/config.yml
                    version: ${{ steps.version_tag.outputs.version_tag }}
                    publish: ${{ github.ref_name != 'dev' }}